### ISSUE TITLE
Duplicate git alias: unmerged

### ISSUE THREAD

**Issue by thombashi** [gggritso/dotfiles#5]
Looks like `gitconfig.symlink` has two `unmerged` alias definitions:

```
$ cat gitconfig.symlink | grep unmerged
30:  unmerged = branch --no-merged
41:  unmerged = diff --name-only --diff-filter=U
```

**Comment by gggritso** [comment]
Right you are! Updated in `dd1318e3673d74bcc321e896f8e9d72dfb85001e` which disambiguates and updates the second alias. Thank you!
